# Generated by Django 5.1.4 on 2025-02-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.IntegerField(verbose_name='Диаметр трубы (мм)')),
                ('length', models.FloatField(verbose_name='Длина участка (м)')),
                ('insulation_material', models.CharField(choices=[('mineral_wool', 'Минеральная вата'), ('polyurethane', 'Пенополиуретан'), ('foamglass', 'Пеностекло'), ('none', 'Без изоляции')], max_length=50, verbose_name='Теплоизоляционный материал')),
                ('laying_type', models.CharField(choices=[('underground', 'Подземная'), ('aboveground', 'Наземная'), ('channel', 'В канале')], max_length=20, verbose_name='Тип прокладки')),
                ('commissioning_year', models.PositiveIntegerField(verbose_name='Год ввода в эксплуатацию')),
            ],
        ),
    ]
