# Generated by Django 5.1.4 on 2025-02-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.PositiveIntegerField(unique=True, verbose_name='Диаметр трубы, мм')),
                ('specific_volume', models.FloatField(verbose_name='Удельный объем, куб. м/км')),
            ],
            options={
                'verbose_name': 'Стандартная труба',
                'verbose_name_plural': 'Стандартные трубы',
                'ordering': ['diameter'],
            },
        ),
        migrations.AlterField(
            model_name='pipelinesegment',
            name='insulation_material',
            field=models.CharField(choices=[('Минеральная вата', 'Минеральная вата'), ('Пенополиуретан', 'Пенополиуретан'), ('Пеностеклоs', 'Пеностекло'), ('Без изоляции', 'Без изоляции')], max_length=50, verbose_name='Теплоизоляционный материал'),
        ),
        migrations.AlterField(
            model_name='pipelinesegment',
            name='laying_type',
            field=models.CharField(choices=[('Подземная', 'Подземная'), ('Наземная', 'Наземная'), ('В канале', 'В канале')], max_length=20, verbose_name='Тип прокладки'),
        ),
        migrations.AlterField(
            model_name='pipelinesegment',
            name='length',
            field=models.FloatField(verbose_name='Длина участка (км)'),
        ),
    ]
