# Generated by Django 5.1.4 on 2025-02-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0002_pipestandard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование котельной')),
                ('pipe_type', models.CharField(choices=[('Подающий', 'Подающий'), ('Обратный', 'Обратный')], max_length=10, verbose_name='Тип трубопровода')),
                ('january', models.IntegerField(default=0, verbose_name='Январь')),
                ('february', models.IntegerField(default=0, verbose_name='Февраль')),
                ('march', models.IntegerField(default=0, verbose_name='Март')),
                ('april', models.IntegerField(default=0, verbose_name='Апрель')),
                ('may', models.IntegerField(default=0, verbose_name='Май')),
                ('june', models.IntegerField(default=0, verbose_name='Июнь')),
                ('july', models.IntegerField(default=0, verbose_name='Июль')),
                ('august', models.IntegerField(default=0, verbose_name='Август')),
                ('september', models.IntegerField(default=0, verbose_name='Сентябрь')),
                ('october', models.IntegerField(default=0, verbose_name='Октябрь')),
                ('november', models.IntegerField(default=0, verbose_name='Ноябрь')),
                ('december', models.IntegerField(default=0, verbose_name='Декабрь')),
            ],
            options={
                'verbose_name': 'Температурный график',
                'verbose_name_plural': 'Температурные графики',
            },
        ),
    ]
