# Generated by Django 5.1.4 on 2025-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0004_alter_pipelinesegment_insulation_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsulationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Вид материала')),
                ('thermal_conductivity', models.FloatField(verbose_name='Теплопроводность, Вт/(м·°С)')),
            ],
            options={
                'verbose_name': 'Материал изоляции',
                'verbose_name_plural': 'Материалы изоляции',
            },
        ),
    ]
