# Generated by Django 5.1.4 on 2025-03-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0005_insulationmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatTransferCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('Вода в трубе', 'Вода в трубе'), ('Подземная прокладка', 'Подземная прокладка'), ('Наземная прокладка', 'Наземная прокладка'), ('В канале', 'В канале')], max_length=50, unique=True, verbose_name='Тип среды')),
                ('alpha', models.FloatField(verbose_name='Коэффициент теплоотдачи, Вт/(м²·°С)')),
            ],
            options={
                'verbose_name': 'Коэффициент теплоотдачи',
                'verbose_name_plural': 'Коэффициенты теплоотдачи',
            },
        ),
    ]
