# Generated by Django 5.1.4 on 2025-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0006_heattransfercoefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinesegment',
            name='insulation_material',
            field=models.CharField(choices=[('Минеральная вата', 'Минеральная вата'), ('Пенополиуретан', 'Пенополиуретан'), ('Пеностекло', 'Пеностекло')], max_length=50, verbose_name='Теплоизоляционный материал'),
        ),
    ]
