# Generated by Django 5.1.4 on 2025-03-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0007_alter_pipelinesegment_insulation_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatLossInsulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.FloatField(verbose_name='Коэффициент b')),
                ('insulation_thickness_mm', models.FloatField(verbose_name='Толщина слоя теплоизоляционного материала (мм)')),
                ('heat_loss_supply', models.FloatField(blank=True, null=True, verbose_name='Удельные теплопотери (поддающий трубопровод) ккал/(м·ч)')),
                ('heat_loss_return', models.FloatField(blank=True, null=True, verbose_name='Удельные теплопотери (обратный трубопровод) ккал/(м·ч)')),
                ('pipeline_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat_losses_app.pipelinesegment')),
            ],
        ),
    ]
