# Generated by Django 5.1.4 on 2025-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0008_heatloss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatlossinsulation',
            name='heat_loss_return',
            field=models.FloatField(verbose_name='Удельные теплопотери (обратный трубопровод) ккал/(м·ч)'),
        ),
        migrations.AlterField(
            model_name='heatlossinsulation',
            name='heat_loss_supply',
            field=models.FloatField(verbose_name='Удельные теплопотери (поддающий трубопровод) ккал/(м·ч)'),
        ),
        migrations.AlterField(
            model_name='pipelinesegment',
            name='laying_type',
            field=models.CharField(choices=[('Подземная прокладка', 'Подземная прокладка'), ('Наземная прокладка', 'Наземная прокладка'), ('В канале', 'В канале')], max_length=20, verbose_name='Тип прокладки'),
        ),
    ]
