# Generated by Django 5.1.4 on 2025-03-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0009_alter_heatlossinsulation_heat_loss_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictPipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_insulation_material', models.CharField(choices=[('Пенополиуретан', 'Пенополиуретан')], default='Пенополиуретан', max_length=50, verbose_name='Новый теплоизоляционный материал')),
                ('replacement', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3, verbose_name='Замена трубопровода')),
                ('heat_loss_supply', models.FloatField(verbose_name='Удельные теплопотери (поддающий трубопровод) ккал/(м·ч)')),
                ('heat_loss_return', models.FloatField(verbose_name='Удельные теплопотери (обратный трубопровод) ккал/(м·ч)')),
                ('heat_loss_year', models.FloatField(verbose_name='Годовые нормы тепловых потерь Гкал')),
                ('pipeline_segment_loss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heat_losses_app.heatlossinsulation')),
            ],
        ),
    ]
