# Generated by Django 5.1.4 on 2025-03-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_losses_app', '0010_predictpipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatlossinsulation',
            name='heat_loss_year',
            field=models.FloatField(null=True, verbose_name='Годовые нормы тепловых потерь Гкал'),
        ),
    ]
