# Generated by Django 5.1.4 on 2025-02-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('numbers', models.IntegerField()),
                ('construction_volume', models.IntegerField()),
                ('indoor_air_temperature', models.IntegerField(default=20)),
                ('construction_year', models.IntegerField()),
                ('heating_characteristic', models.FloatField()),
            ],
        ),
    ]
