# Generated by Django 5.1.4 on 2025-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Параметры дома', 'verbose_name_plural': 'Параметры дома'},
        ),
        migrations.AlterField(
            model_name='home',
            name='construction_volume',
            field=models.IntegerField(verbose_name='Строительный объем'),
        ),
        migrations.AlterField(
            model_name='home',
            name='construction_year',
            field=models.IntegerField(verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='home',
            name='heating_characteristic',
            field=models.FloatField(editable=False, verbose_name='Удельная отопительная характеристика'),
        ),
        migrations.AlterField(
            model_name='home',
            name='indoor_air_temperature',
            field=models.IntegerField(default=20, verbose_name='Внутренняя температура воздуха'),
        ),
        migrations.AlterField(
            model_name='home',
            name='numbers',
            field=models.IntegerField(verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='home',
            name='street_name',
            field=models.CharField(max_length=255, verbose_name='Улица'),
        ),
    ]
