# Generated by Django 5.1.4 on 2025-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermo', '0002_alter_home_options_alter_home_construction_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='heat_energy',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Тепловая энергия'),
            preserve_default=False,
        ),
    ]
