# Generated by Django 5.1.4 on 2025-03-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermo', '0003_home_heat_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerRoomPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_type', models.CharField(max_length=50)),
                ('pump_category', models.CharField(choices=[('подпиточный', 'Подпиточный'), ('сетевой', 'Сетевой')], max_length=20)),
                ('power_kW', models.FloatField()),
                ('operating_hours', models.PositiveIntegerField()),
            ],
        ),
    ]
