# Generated by Django 5.1.4 on 2025-03-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermo', '0004_boilerroompump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerroompump',
            name='operating_hours',
            field=models.PositiveIntegerField(verbose_name='Продолжительность работы'),
        ),
        migrations.AlterField(
            model_name='boilerroompump',
            name='power_kW',
            field=models.FloatField(verbose_name='Мощность двигателя'),
        ),
        migrations.AlterField(
            model_name='boilerroompump',
            name='pump_category',
            field=models.CharField(choices=[('подпиточный', 'Подпиточный'), ('сетевой', 'Сетевой')], max_length=20, verbose_name='Вид насоса'),
        ),
        migrations.AlterField(
            model_name='boilerroompump',
            name='pump_type',
            field=models.CharField(max_length=50, verbose_name='Модель насоса'),
        ),
    ]
